language: java
jdk:
  - openjdk11
branches:
  only:
    - master
notifications:
  email: false
  slack:
    rooms:
      - secure: n7szQGsGAbxzZv/NSNvJQGPDwQPNqksAzLjmeViMmHX0malUW1DMkEObNpvNcrWRODJvAi+T6bYvw5cK0SzOa9rezYNVNVvZUgzdSvm9cBI0h8JJLvdk+y6hMLpy+za+6ZFEDjDyeOJNcnNdmtNj4gQXFTeHtcrk5Fqps2wUxnm3AtcNEznE1pidAlt3QBQ0FXiq0SEI5s6txSmMZCt4aFaa4Iqs/TA3aiCEkwLu8JdNbf5xlfoIQSQPB47vGWzIsd29OKaUyzGU80v8bGwLrHv4JrM6U52CFXwHYBwrAlx75p/kmv1S/8hBJ0Y0zIQYpppSJdx8L9w+iDbqmfdYu333kJdyaYhkFKMjyR+oFbjRCXlHtM+tb30BIbhH337/uma+cEKwDkPgI241R3J5b6B1l15E1xeaWiYg7V8sMUcmeXLtIwDO0PygRCP5NocNCGhG/Q8S0+IpWw/o1tT4uRb1HfruUp3pz3xVoiWE9SfjAgBX0VKciDa+a6oVHOytuZSwRWAi6H2LLyhDVOqt89EKyyEcJJshNNtioDCgW8OWhNRjFOk8h0tx+AZ+VDNPxDlBpNZceVZ2XNKh5bpEPnjfprKj0eqFwfoGy63g6MZ66Rj7a/Yc06J5zWtD9tnTAJyaelptyqwaS6ji+ngk8woSH5lgT+x4SflwF5i5R5Y=
addons:
  sonarcloud:
    organization: delegacy-github
    token:
      secure: eMXBgzmGwoYXnACqX3noOG2HvMOU9DdlWloOnTjP7VfUoLtxI199tVDfmL4oZm86qHQ6pqaLL7mYea4fHZ9oeI6MACwTgPKLZx3En3ERslYZQZ96dkJYT77itnFeGHQFs73CJ9rsTGFwgX+2i/SMyL8urmAekDN1/H3BL4KoCTo7ouMIgOrEnb13IJqwnEAN1FZffHk9cUXrOxRHdxRgTFXv7XYJq+PFxMaMP9mxbpxhi6qfr11taLnPccZHzijKap8E0m3Y8viHnOf1TZb2ftuT7oocO6O+Wqcq5Fmv2fjwBnE4V/4h81RT5Lo09m0V+UTgf50Hv3zx8mE1ketYBE6p1pawQEjOyd3RZH8h1t0vyH6NfYbKmbTfPb5hDJikiUpuzRPv86ksKi9eObgFZjmD3QaEsV4UdOKZjOm7nvtUD55lQUZE4CBOVc4+SCaYlzHkOCM2520Ps/JpHhj0weNBXt6nOy29DiJiLxb+QwI2cv77sQL1asFlA8/gJtitTuGcon2Fm8ucJF9XDHf/tdMJ2pntD4e2ytiEZ6DWsQdNWiOVw4bkpOW93Ete2AwKlWXuyV0Hv05HP9QTA7yFZAOhKvPzPdHNIGJjE42O9m2qtBmmrNsrsnyrr8Gz9pcWVJdqYFCWybMw4i1KCdE7oNDh1bx2Pbszf/EL6tbZbGw=
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - secure: k8TAhQ8AT1vqgIBRzNgR+f6Li4FTml9o7azcYFRhicep8ohx1WquXr5JGcyXXc1esrv/h3dgCyNLZjXd7oM3VcNUp0Z0DqI2LfRQ4dX93L8wky5ZOQNzThnnn2iDgRBtrc6zeaGY15gwei30bgiglKLJcewugzp7BVVF5E1ZQiOqZykkAYuk5OyXUTSG6sngcOIXuT3vc5ndXNLFv44ySDyQc+aWzFvAVOfD+MA/4ffhktLQEgs8jmS8ghnrVZuKI0RbfT9fYmq/4dWK+AjHPYUf6Z0wbqN/x63k+tkvxx7kRuch8aGz5r04CfhUP6chnaq4toegygAaABRUr6Mo1WRmV4avfqZFRR+C6zU1aRi1CpTSEpxghX8xmuMU1uq3KkWK15+yu9IvTYpfE4A8PqWRSS9dfK/faEGT7NatIfh0Z1clZ7CdZkspFyo3ZpfohlaBhgQoMX7EBKC+AgJraDa5SEzDIsYeNMXLm1wBQAyf8lt6wyrBXRuaRGPWsWMxWOqok2a7IMeoiHMdF8rFIXcGZxqL4VCyV7aIk6yR7JlGAVe3Td9pwkGt4ezFS27KqAGO1ZKnj8yvlb1UCY1S/mdkd8xv5SZ5vqnYAJ1AiQ4aMbsS5W37bmaOxloBZmKqy89j363rPP+8UyLfx6LTmu1k9FaC5vW9ZGN9YuAnyWc= # DOCKER_USERNAME
    - secure: Z9Vx1jBYydfxzOmwLSfEZKSRwfXhg3rRcs0opmJ1LvCNXvwzlgJUW9/Y7paH3Aevo7/7a719W+9SDG9CDHnVP7+BCwFaTF8YG3LW0lcaRy8aQ6ONlnFfQaDYiv9yfHwVgcYcINSpMpyc9sXO1y/mx0EA9KqvRMql9HCjFwBrGotzw1VdeCAqpoZGhADfmcCJkxb7gn0Jzw5tzRIZ1MVFJEdMxv3FTPcawFfOWYxz6s1NIN4v86tGDMNezVjHzrRff0u5QNdpc8/Clgn8D1lzTKJPo9s8C7u1H9W9CflsNG4ZaCTYw9cMYvzgBeR/2UxFl5UMg/ppYlGMBzLSiGF0kjQCBwXuUSkpYdaZvxthkiNvN5mxRtKTeDKX8FsMzpxmpS3V2PrlUedTaZ4RHSNhwxPGk1huxISJhflU+D4lcoBvuLI/H/H0z1bTrBrF2b0yFJc61OUtSFydoMIjfr+NZ30w21xj5Ot2XQk/l+zejmFBlMUrm2TRf1nvaM1dRSrqABv8bHKe3yHBJaC37dlZPBlLNVaOlnrvK7zizgu8yWBhwwPkLwBQy+cEwPqWavsJtHJpH3mIH66ypzPX4003YXU2MLh9X1cBk3siKdvvzF81Lfy/lHSWhvnwjEjVZOyiUhj3gPUyZ+uBsGCqVRms+YXt9qd6C82cp31i+3KPXoA= # DOCKER_PASSWORD
    - secure: SIjGDC47SOOONLVk/A6nJHMY60yjVr1+Op2sldjyAUy+2sSZrAVbZ7Fv8KUPLE/BOwQfTRhtlG6swejacrUU64ggQAJzpFmugiq0jyEQd5CxvxgueE0hJ8S60wKcW3j+Udcwxe7kzvqTJz3+rmTV/U5S+ZZHaypbAiJNxcs/xLCfYtsEqnU2spiN8tXw8+WPYWY1W/t/Xa+9rh8WW2UCfqFPKsncfptTy0pzfSlmGb3fhI4n9fildbWju4WGbAkp7MxuY9Yuorj/rsFlyk3jwg1TlDPcsXMd/KSGp+pJoFeatSY4xxmNPe7ydZmTYZCj+gincu86XHosmVfbdRb2TmMCO/ZYYq11aaI6v4mVBmOjQQJaTujkJD0W0ASU2SbSUiTBTPuqe+nY9oGV3xeaPogOJNhKSl5mMh5RZklqZ7LcTYC0dsEL9V6ts1tgrXplfGklU1w3lY+CI3cNPKR4kVGh7FRpsyQW3Cx2N0LQPvduBX6OWfO5jJNt1n0ch7qAzfRd5tLJZO74SXWsF8bv4Hp1yUGNLZhByXwKml59zQwG6sMGTNTABbmlNHT4vdkhMJc8DMNQQWUH1H6N5sdOyGhqtuQn5Y55Ixrx9u0YSu0NIRmfzhwahRL/cfLG72Mdc68T8RGTTMMcN/pLyjSgqOKfUiQ9t/ydmolVTNs1b8M= # CODECOV_TOKEN
    - secure: wtwURyqhDgU4rBtWb6bt9XFDv0Kbwzk2Hmk57vzMzCPrpYRRSJSdbuX5Z3ae9/fq2CsYBKUil1jZw9cfKTFfRz7cbOZ624r1tGpp/Nqg5fnDa/Ohj85/eb33nB8c96sHBvz8vJGkIamgERMSCW++701h6ZzeRljEJCr4xgG1PqLg0AqUyOVlxdAI6m5R7JJVfOxUadY9upqfMDigb5OJjMvBiY0DppwRlWuF6MZcqgTiUcSVnQOXviM5LvAgIzkwRAZB6oJW78vAfL+OfAXOM9TmruYaSyNfcW7P5xvTBp/YqAdCtD3/BxpsAmtlw6GkqUhS8A+ZoF76DpPrtsb/8c89KSGxkefpxDri4TKGtqBCDUaAPAD24OdsoYubuZRE+76kcomZ0UooroHY3fAZhf0UC2HEkijE3PR3Q/4SbX/GRPESqVakdO3q7jZliUN+hqYn446YNimzB+8zFOxYpkuD92oXd38B6hbQrxpks6aZ3mb5fRSd1jSBDE8j3fRL+Lm473S/FpZnpQSf8nkyENM3PWWkSsmOoM9d/GJlQiBomnHyngRFmKvkVFKCKy39Bs4yCjqMNFQ/waxvdVEbckwipS7QXMNvrbRtA12/CSyWOnFVXVElJqjnVqM+Dejov3eK3lfHL9h+v4onAb8tAHJaKCSdWC8U5J41+d5j0Jo= # ANSIBLE_VAULT_PASSWORD
before_cache:
  - find $HOME/.gradle/caches -name '*.lock' -delete
cache:
  directories:
    - "$HOME/.gradle/wrapper/dists"
    - "$HOME/.gradle/caches/jars-3"
    - "$HOME/.gradle/caches/modules-2"
    - "$HOME/.gradle/caches/package-lists"
script:
  - "./gradlew --no-daemon --stacktrace --warning-mode=all check build sonarqube"
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - pip install --user ansible botocore boto boto3
deploy:
  skip_cleanup: true
  provider: script
  script: "./gradlew dockerPushImage -x test && cd ansible-playbook && ./ansible-playbook.sh --vault-id ./vault-password.py ecs.yml"
  on:
    branch: master
