server:
  port: ${PORT:28080}

youngbot:
  slack:
    client:
      base-uri: https://slack.com/api
      bot-token: bot-token
  line:
    channel-token: channel-token
    channel-secret: channel-secret
    client:
      base-uri: https://api.line.me

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    com.github.delegacy.youngbot.server: DEBUG

cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false

management:
  metrics:
    export:
      cloudwatch:
        enabled: false
        namespace: young-bot
        batchSize: 20
