server:
  port: ${PORT:28080}
  ssl:
    enabled: false

armeria:
  ports:
    - port: ${HTTP_PORT:0}
      protoco: HTTP

youngbot:
  slack:
    bot-token: bot-token
    signing-secret: signing-secret
    rtm:
      enabled: false
  line:
    channel-token: channel-token
    channel-secret: channel-secret
    client:
      base-uri: https://api.line.me

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    com.github.delegacy.youngbot.server: DEBUG
    com.linecorp.bot.client.wire: WARN

cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, loggers
  health:
    db:
      enabled: false
  metrics:
    export:
      cloudwatch:
        enabled: false
        namespace: young-bot
        batchSize: 20

---

spring:
  profiles: prod

logging:
  level:
    com.github.delegacy.youngbot.server: INFO
